spring.application.name=studentcourseapp

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console to view DB in browser i am using H2 for fast development and testing
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always